### ISSUE TITLE
gulp-babel error 

### ISSUE THREAD

**Issue by Audesch** [TechDWM/gulp-starter#1]
J'ai un problème quand je run le gulp watch, il m'affiche une erreur "Error: Cannot find module '@babel/core' ". Malgré le fait que je l'installe manuellement, l'erreur revient tout le temps et m'empêche alors de lancer le serveur local. 

J'ai vérifié que le dossier @babel soit bien installé, il l'est mais il ne présente pas de dossier "core". 

Pouvez-vous m'aider sur ce point ?

**Comment by lemagus** [comment]
Il doit manquer le module @babel/core lors de l'installation. 
Essaie de lancer la commande suivante:

`npm install --save-dev @babel/core`

Et plus globalement, lorsque une erreur de ce genre surgit, essaie de lancer la commande

`npm install --save-dev **le-nom-du-module-manquant-dans-l-erreur**`

Ca résout généralement les soucis :-)
